### ISSUE TITLE
Some tips

### ISSUE THREAD

**Issue by mawoka-myblock** [dkaloger/WallpaperOS#2]
- Do not include binaries (the .exe-file) in got, upload them separately in Releases
- Rename `Source Code` to `src`
- Point out, that it only works on Windows
- Write instructions on how to create the .exe-file or create the file using GitHub Actions
- add a requirements.txt
- publish the package on pypi

**Comment by dkaloger** [comment]
Thanks for the tips , I will be implementing most of them but I believe including the build is better since I will be using an auto updater which fetches the latest release version(when the Version.txt file is Updated) from Github.

**Comment by mawoka-myblock** [comment]
> Thanks for the tips , I will be implementing most of them but I believe including the build is better since I will be using an auto updater which fetches the latest release version(when the Version.txt file is Updated) from Github.

I don't think so. You can easily use the GitHub-API to get the latest release and download it from there. A Version.txt also creates a huge mess in the git-history. If you have any further questions, I'm happy to help, and, I know, setting up CI is a really time-consuming and annoying job, but it's worth it.

**Comment by dkaloger** [comment]
> > Thanks for the tips , I will be implementing most of them but I believe including the build is better since I will be using an auto updater which fetches the latest release version(when the Version.txt file is Updated) from Github.
> 
> I don't think so. You can easily use the GitHub-API to get the latest release and download it from there. A Version.txt also creates a huge mess in the git-history. If you have any further questions, I'm happy to help, and, I know, setting up CI is a really time-consuming and annoying job, but it's worth it.

Apart from potential issues with the Version.txt what are the other problems that could arise? I have already created the updater and installer and was about to publish them.

**Comment by mawoka-myblock** [comment]
> > > Thanks for the tips , I will be implementing most of them but I believe including the build is better since I will be using an auto updater which fetches the latest release version(when the Version.txt file is Updated) from Github.
> > 
> > 
> > I don't think so. You can easily use the GitHub-API to get the latest release and download it from there. A Version.txt also creates a huge mess in the git-history. If you have any further questions, I'm happy to help, and, I know, setting up CI is a really time-consuming and annoying job, but it's worth it.
> 
> Apart from potential issues with the Version.txt what are the other problems that could arise? I have already created the updater and installer and was about to publish them.

I don't know, I just think it's clearner to use Githubs Release-feature, but it's your project and go ahead, publish it!
