### ISSUE TITLE
Hello  - How to uninstall 

### ISSUE THREAD

**Issue by akvariefisk** [dkaloger/WallpaperOS#4]
The script give me 

raceback (most recent call last):
  File "WallpaperOS.py", line 14, in <module>
  File "PIL\Image.py", line 3147, in open
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000255FEEA4040>

How to remove it completely?

**Comment by atotheframe** [comment]
Hi, I'm experiencing the same issue. Same error message unfortunately.

I would love a way to either remove the error message every time I login to Windows or a fix. Thank you! Please let me know if you need any more info.

Running Windows 11 (Version 22H2 Build 22621)
