### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by atotheframe** [dkaloger/WallpaperOS#5]
Hi, I'm seeing this error message when I run the installer.exe on Windows 11 Pro 22H2 (Build 22621.521):

Traceback (most recent call last):
  File "WallpaperOS.py", line 14, in <module>
  File "PIL\Image.py", line 3147, in open
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002726CE13BA0>

Any assistance appreciated, thanks!

**Comment by drewski-00h** [comment]
Same!

![Screenshot (155)](https://user-images.githubusercontent.com/83047636/200082982-4a3afc07-beee-4e0c-a97d-70d47e5a8fc4.png)
